### ISSUE TITLE
디자인 기여

### ISSUE THREAD

**Issue by dungsil** [byulmaru/share#1]
안녕하세요! 
우선 멋진 서비스를 만들어 주셔서 감사합니다!

현재 서비스에 따로 스타일은 없어서 혹시 CSS 관련하여 기여하고 싶은데 혹시 따로 진행중 이실지 혹은 기여를 받고 계신지에 대하여 문의 남깁니다.

**Comment by robin-maki** [comment]
지금은 디자인 관련된 작업을 따로 진행하고 있지 않아서 디자인 관련 PR을 보내주신다면 정말 감사드릴 거 같아요!
